load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "StringGenerator",
    module_name = "StringGenerator",
    srcs = ["StringGenerator.swift"],
    visibility = ["//visibility:public"]
)
